Starting pipeline donors-choose (f434fc0c-3459-41f2-a45e-83aa72349efc) at 2019-05-01 17:55:58.545348
Input data: /Users/satej/Documents/workspace/classwork/machine-learning/capp30254/hw3/code/input/projects_2012_2013.csv (SHA-256: b34fdb1924369afb5df5a1ba886f7269b7455b9baf2fd2248bc3409fcfa8f18f)
Pipeline library version: db887e6

Pipeline settings:
    summarize: True
    data_preprocessors: []
    feature_generators: []
    model: None
    name: donors-choose
    output_root_dir: /Users/satej/Documents/workspace/classwork/machine-learning/capp30254/hw3/code/output

Loading data
Summarizing data.

Running transformations for preprocessing


Running transformations for feature generation

Evaluating model
