Starting pipeline donors-choose-preprocessing (d119ee94-03b4-495e-aee2-b17b2420c472) at 2019-05-02 02:42:37.793100
Input data: /Users/satej/Documents/workspace/classwork/machine-learning/capp30254/hw3/code/input/projects_2012_2013.csv (SHA-256: fed125d8b399ece97c283314dec6bf5a56d8cdd3d2335f1f4d43d18f6a1b4ef0)
Pipeline library version: b6fd078

Pipeline settings:
    summarize: True
    data_preprocessors: [categorize-school_city, categorize-school_state, categorize-school_metro, categorize-primary_focus_subject, categorize-primary_focus_area, categorize-resource_type, categorize-poverty_level, categorize-grade_level, binarize-school_charter, binarize-school_magnet, replace-missing-values-with-value(students_reached,0), binarize-eligible_double_your_impact_match, month_posted, funded_in_60_days]
    feature_generators: None
    model: None
    name: donors-choose-preprocessing
    output_root_dir: /Users/satej/Documents/workspace/classwork/machine-learning/capp30254/hw3/code/output

Loading data
Summarizing data.

Running transformations for preprocessing
    Applying transformation (1/14): categorize-school_city 
    ['school_city'] -> school_city_categorical
