data: 
  input_path: "./input/projects_2012_2013.csv"
  output_dir: "./output/"

pipeline:
  name : "donors_choose"
  target: "funded_in_60_days"
  test_train:
    split_column: "date_posted"
    splits: 
      - train: 
          start: 01/01/2012
          end:   04/01/2012
        test: 
          start: 06/01/2012
          end:   12/31/2012
      - train: 
          start: 01/01/2012
          end:   10/01/2012
        test: 
          start: 01/01/2013
          end:   12/31/2013
      - train: 
          start: 01/01/2012
          end:   04/01/2013
        test: 
          start: 06/01/2013
          end:   12/31/2013

models: 
  LinearSVC:
    C: [0.01, 0.1, 1, 10, 100]
    penalty: ["l2"]    

  LogisticRegression:
    C: [0.01, 0.1, 1, 10, 100]
    penalty: ["l1", "l2"]
    n_jobs: [-1]

  KNeighborsClassifier: 
    n_neighbors: [10, 50, 100]
    n_jobs: [-1]

  DecisionTreeClassifier:
    max_depth: [null, 1, 5, 10, 50, 100]

  GradientBoostingClassifier:
    learning_rate: [0.1, 0.5, 2.0]
  
  BaggingClassifier:
    max_samples: [0.1, 0.5, 1.0]
    n_jobs: [-1]

  RandomForestClassifier:
    n_estimators: [10, 100, 1000]
    max_depth: [null, 1, 5, 10, 50, 100]
    n_jobs: [-1]
