Starting pipeline financial-distress-classifier (84a683bb-46f7-40b1-a8a3-da4b18429914) at 2019-04-15 21:13:12.652571
Input data: /Users/satej/Documents/workspace/classwork/machine-learning/capp30254/hw2/code/input/credit-data.csv (SHA-256: 28a118cf214a46179ac4d374f3d75f86edb81f219764cf397e1cc8f3d928f44b)
Pipeline library version: 1ae3eb5

Pipeline settings:
    summarize: True
    data_preprocessors: [replace-missing-values-with-mean(MonthlyIncome), replace-missing-values-with-mean(NumberOfDependents), log-monthly-income]
    feature_generators: []
    model: None
    name: financial-distress-classifier
    output_root_directory: /Users/satej/Documents/workspace/classwork/machine-learning/capp30254/hw2/code/output

Loading data
Summarizing data to output/financial-distress-classifier-84a683bb-46f7-40b1-a8a3-da4b18429914/summary.csv

Running transformations for preprocessing
    Applying transformation (1/3): replace-missing-values-with-mean(MonthlyIncome) 
    ['MonthlyIncome'] -> MonthlyIncome_clean
    Applying transformation (2/3): replace-missing-values-with-mean(NumberOfDependents) 
    ['NumberOfDependents'] -> NumberOfDependents_clean
    Applying transformation (3/3): log-monthly-income 
    ['MonthlyIncome_clean'] -> logMonthlyIncome


Running transformations for feature generation

Copying artifacts to stable path
Finished at 2019-04-15 21:13:12.805937
