Starting pipeline 1-donors-choose-exploration (8f1cc25d-df20-4c7b-9aa9-647bb086a0d4) at 2019-05-02 12:21:35.040072
Input data: /Users/satej/Documents/workspace/classwork/machine-learning/capp30254/hw3/code/input/projects_2012_2013.csv (SHA-256: b34fdb1924369afb5df5a1ba886f7269b7455b9baf2fd2248bc3409fcfa8f18f)
Pipeline library version: 0b9d0ef

Pipeline settings:
    summarize: True
    data_preprocessors: None
    feature_generators: None
    model: None
    name: 1-donors-choose-exploration
    output_root_dir: /Users/satej/Documents/workspace/classwork/machine-learning/capp30254/hw3/code/output

Loading data from existing data frame
Running custom summary function
Copying artifacts to stable path
