Starting pipeline donors-choose (b2f86cf0-bdca-4363-a49f-9204c6b2565b) at 2019-05-01 17:54:20.731530
Input data: /Users/satej/Documents/workspace/classwork/machine-learning/capp30254/hw3/code/input/projects_2012_2013.csv (SHA-256: b34fdb1924369afb5df5a1ba886f7269b7455b9baf2fd2248bc3409fcfa8f18f)
Pipeline library version: db887e6

Pipeline settings:
    summarize: True
    data_preprocessors: []
    feature_generators: []
    model: None
    name: donors-choose
    output_root_dir: /Users/satej/Documents/workspace/classwork/machine-learning/capp30254/hw3/code/output

Loading data
Summarizing data.

Running transformations for preprocessing


Running transformations for feature generation

Running model None
Features: []
Fitting: temp
